### ISSUE TITLE
Suggestion: Installation / compiling instructions

### ISSUE THREAD

**Issue by sbrl** [bitnami/bcrypt-cli#13]
In order for people to use bcrypt-cli, they must first compile it. Giving instructions is helpful to let people know how to do this.

**Comment by alvneiayu** [comment]
hi @sbrl 

Thanks a lot for your suggestion. We are going to include more details inside the README. Meantime, the way to build the project is:

```
make build
```

I will let you know, when the PR is available adding the information requested.

Thanks a lot

Álvaro
