### ISSUE TITLE
How to create $2y hashes

### ISSUE THREAD

**Issue by marmelin** [bitnami/bcrypt-cli#14]
Hi there , 

I wondered how to create hashes with `$2y...` entity instead of `$2a...`?

**Comment by marcosbc** [comment]
Hi @marmelin, note that we are not actively maintaining this tool at this moment. If you would like this feature to be supported, feel free to send a PR, we would be happy to review it.

**Comment by marcosbc** [comment]
Hi @marmelin, unfortunately we are deprecating this tool as mentioned in #15. The repository will remain publicly available, but will be in an archived state. We encourage you to look for alternatives, but if you cannot find any, feel free to fork this project and maintain it on your side.
